export const PROFILE = {
    "profileName": "prod",
    "extensionId": "owlvex.owlvex",
    "configSection": "owlvex",
    "displayLabel": "Owlvex",
    "statusBarLabel": "Owlvex Prod",
    "activityBarIcon": "media/owlvex-prod.svg",
    "defaultApiUrl": "https://owlvex-api.azurewebsites.net",
    "storagePrefix": "owlvex",
    "secretPrefix": "owlvex",
    "diagnosticCollection": "owlvex",
    "viewContainerId": "owlvex",
    "findingsViewId": "owlvex.findings",
    "chatViewId": "owlvex.chat",
    "comparisonPanelId": "owlvexComparison",
    "commands": {
        "scanFile": "owlvex.scanFile",
        "scanWorkspace": "owlvex.scanWorkspace",
        "scanWorkspaceReport": "owlvex.scanWorkspaceReport",
        "selectFrameworks": "owlvex.selectFrameworks",
        "openPromptEditor": "owlvex.openPromptEditor",
        "switchModel": "owlvex.switchModel",
        "setupAI": "owlvex.setupAI",
        "testAI": "owlvex.testAIConnection",
        "enterLicence": "owlvex.enterLicence",
        "compareScans": "owlvex.compareScans",
        "reviewRiskCalibration": "owlvex.reviewRiskCalibration",
        "discussFinding": "owlvex.discussFinding",
        "revealLine": "owlvex.revealLine",
        "chatFocus": "owlvex.chat.focus"
    }
} as const;
