export interface CanonicalMappings {
    cwe: string[];
    owasp: string[];
    apiOwasp: string[];
    attack: string[];
    capec: string[];
    nist: string[];
}

export interface CanonicalIssue {
    id: string;
    slug: string;
    title: string;
    category: string;
    family: string;
    severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';
    stride: string[];
    mappings: CanonicalMappings;
    keywords: string[];
    remediationSummary: string;
    cheatSheetRefs: string[];
    requiredAnyKeywords?: string[];
    negativeKeywords?: string[];
    minimumScore?: number;
}

export interface IssueFamilyDefinition {
    id: string;
    label: string;
    description: string;
}

export const ISSUE_FAMILY_CATALOG: IssueFamilyDefinition[] = [
    {
        id: 'family.secrets_exposure',
        label: 'Secrets & Credential Exposure',
        description: 'Hardcoded credentials, token leakage, and other secret-handling weaknesses.',
    },
    {
        id: 'family.injection_execution',
        label: 'Injection & Execution',
        description: 'Injection flaws that let untrusted input alter queries, commands, templates, or interpreters.',
    },
    {
        id: 'family.identity_auth',
        label: 'Identity & Auth Failures',
        description: 'Authentication weaknesses, token validation errors, and account compromise paths.',
    },
    {
        id: 'family.access_control',
        label: 'Access Control & Authorization',
        description: 'Object-level authorization, path access, and unsafe permission boundaries.',
    },
    {
        id: 'family.data_protection_privacy',
        label: 'Data Protection & Privacy',
        description: 'Sensitive logging, disclosure, and unsafe handling of protected data.',
    },
    {
        id: 'family.security_misconfiguration',
        label: 'Security Misconfiguration & Platform Hardening',
        description: 'Unsafe defaults, permissive configuration, and weak runtime hardening.',
    },
    {
        id: 'family.audit_observability',
        label: 'Audit & Observability Gaps',
        description: 'Missing audit trails and weak forensic visibility around sensitive actions.',
    },
    {
        id: 'family.availability_resilience',
        label: 'Availability & Resilience',
        description: 'Patterns that create denial of service or systemic resilience risk.',
    },
    {
        id: 'family.crypto_randomness',
        label: 'Cryptography & Randomness',
        description: 'Weak cryptography, unsafe randomness, and broken security primitives.',
    },
];

export const ISSUE_CATALOG: CanonicalIssue[] = [
    {
        id: 'owlvex.issue.sql_injection.001',
        slug: 'sql-injection-unsanitized-query-construction',
        title: 'Unsanitized SQL query construction',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-89'],
            owasp: ['A03:2021'],
            apiOwasp: ['API8:2023'],
            attack: ['T1190'],
            capec: ['CAPEC-66'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['sql injection', 'query', 'parameterized', 'database', 'select * from', 'raw sql'],
        negativeKeywords: ['prepared statement', 'parameter array', 'bound parameter'],
        remediationSummary: 'Use parameterized queries or prepared statements and validate input at trust boundaries.',
        cheatSheetRefs: ['OWASP SQL Injection Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.command_injection.001',
        slug: 'command-injection-unsafe-shell-execution',
        title: 'Unsafe shell command execution',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'CRITICAL',
        stride: ['Tampering', 'Elevation of Privilege', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-78'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-88'],
            nist: ['SI-10', 'CM-7'],
        },
        keywords: ['command injection', 'shell', 'exec(', 'exec ', 'spawn', 'child_process', 'arbitrary commands'],
        negativeKeywords: ['execfile', 'shell: false', 'fixed arguments', 'validated host'],
        remediationSummary: 'Avoid shell invocation where possible; otherwise use non-shell APIs with fixed arguments and strict validation.',
        cheatSheetRefs: ['OWASP OS Command Injection Defense Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_api_key.001',
        slug: 'hardcoded-api-key-in-source',
        title: 'Hardcoded API key in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['api key', 'apikey', 'api_key', 'client secret', 'secret key', 'access key'],
        requiredAnyKeywords: ['api key', 'apikey', 'api_key', 'client secret', 'secret key', 'access key'],
        negativeKeywords: ['username', 'user name', 'admin user'],
        minimumScore: 45,
        remediationSummary: 'Move API keys to a secret manager or environment injection and fail closed if they are missing.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_password.001',
        slug: 'hardcoded-password-in-source',
        title: 'Hardcoded password in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['password', 'dbpassword', 'db password', 'passwd', 'pwd'],
        requiredAnyKeywords: ['password', 'dbpassword', 'db password', 'passwd'],
        negativeKeywords: ['username', 'user name', 'admin user'],
        minimumScore: 45,
        remediationSummary: 'Move passwords to a secret manager or environment injection and fail closed if they are missing.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_token.001',
        slug: 'hardcoded-token-in-source',
        title: 'Hardcoded token in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['token', 'bearer token', 'auth token', 'jwt secret', 'refresh token'],
        requiredAnyKeywords: ['token', 'bearer token', 'auth token', 'jwt secret', 'refresh token'],
        negativeKeywords: ['csrf token generated per request'],
        minimumScore: 45,
        remediationSummary: 'Move static tokens to a secret manager and rotate them out of source control immediately.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_secret.001',
        slug: 'hardcoded-secret-in-source-code',
        title: 'Hardcoded secret in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['hardcoded secret', 'signing key', 'private key', 'embedded secret', 'credential'],
        requiredAnyKeywords: ['hardcoded secret', 'signing key', 'private key', 'embedded secret', 'secret'],
        negativeKeywords: ['username', 'user name', 'admin user', 'display name', 'ops-admin'],
        minimumScore: 55,
        remediationSummary: 'Move secrets to a secret manager or environment injection and fail closed if they are missing.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.path_traversal.001',
        slug: 'path-traversal-untrusted-filesystem-access',
        title: 'Untrusted filesystem path traversal',
        category: 'access-control',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-22'],
            owasp: ['A01:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: ['CAPEC-126'],
            nist: ['AC-6', 'SI-10'],
        },
        keywords: ['path traversal', '../', 'file path', 'path.join', 'filesystem', 'directory boundary'],
        negativeKeywords: ['path.resolve(base', 'startswith(basedir)', 'allow-list'],
        remediationSummary: 'Resolve paths safely, enforce a fixed base directory, and reject traversal attempts.',
        cheatSheetRefs: ['OWASP Path Traversal Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.idor.001',
        slug: 'idor-missing-object-level-authorization',
        title: 'Missing object-level authorization',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Elevation of Privilege', 'Information Disclosure', 'Tampering'],
        mappings: {
            cwe: ['CWE-639'],
            owasp: ['A01:2021'],
            apiOwasp: ['API1:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-233'],
            nist: ['AC-3', 'AC-6'],
        },
        keywords: ['idor', 'object level authorization', 'ownership', 'unauthorized access', 'resource id'],
        negativeKeywords: ['account_id = ?', 'owner_id = ?', 'authorization check', 'policy.enforce'],
        remediationSummary: 'Enforce object-level authorization before read or write operations and scope queries to the authenticated actor.',
        cheatSheetRefs: ['OWASP Authorization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.sensitive_logging.001',
        slug: 'sensitive-data-exposed-in-logs',
        title: 'Sensitive data exposed in logs',
        category: 'logging',
        family: 'family.data_protection_privacy',
        severity: 'MEDIUM',
        stride: ['Information Disclosure', 'Repudiation'],
        mappings: {
            cwe: ['CWE-532'],
            owasp: ['A09:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: [],
            nist: ['AU-9', 'SC-28'],
        },
        keywords: ['log', 'logging', 'sensitive data', 'password in logs', 'token in logs', 'console.log'],
        negativeKeywords: ['redacted', 'masked', '[redacted]'],
        remediationSummary: 'Redact sensitive fields before logging and restrict log content to operationally necessary metadata.',
        cheatSheetRefs: ['OWASP Logging Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.audit_gap.001',
        slug: 'missing-audit-trail-for-privileged-action',
        title: 'Missing audit trail for privileged action',
        category: 'audit',
        family: 'family.audit_observability',
        severity: 'MEDIUM',
        stride: ['Repudiation'],
        mappings: {
            cwe: ['CWE-778'],
            owasp: ['A09:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['AU-2', 'AU-12'],
        },
        keywords: ['audit', 'audit log', 'privileged action', 'traceability', 'no audit', 'missing audit'],
        negativeKeywords: ['audit.log', 'security event', 'immutable audit'],
        remediationSummary: 'Record immutable audit events for privileged actions with actor, action, target, and timestamp metadata.',
        cheatSheetRefs: ['OWASP Logging Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.ssrf.001',
        slug: 'server-side-request-forgery-untrusted-destination',
        title: 'Server-side request forgery through untrusted destination',
        category: 'request-forgery',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Tampering', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-918'],
            owasp: ['A10:2021'],
            apiOwasp: ['API7:2023'],
            attack: ['T1190'],
            capec: ['CAPEC-664'],
            nist: ['SC-7', 'SI-10'],
        },
        keywords: ['ssrf', 'server side request forgery', 'metadata endpoint', 'internal service', 'untrusted url'],
        negativeKeywords: ['allowed_hosts', 'allow-list', 'parsed.hostname'],
        remediationSummary: 'Restrict outbound destinations with allow-lists, block internal address ranges, and normalize parsed URLs before use.',
        cheatSheetRefs: ['OWASP Server Side Request Forgery Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_deserialization.001',
        slug: 'insecure-deserialization-of-untrusted-data',
        title: 'Insecure deserialization of untrusted data',
        category: 'deserialization',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Elevation of Privilege', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-502'],
            owasp: ['A08:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-586'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['deserialization', 'deserialize', 'pickle', 'untrusted payload', 'binary formatter'],
        negativeKeywords: ['json.parse', 'schema validation', 'signed payload'],
        remediationSummary: 'Avoid unsafe deserializers, prefer safe data-only formats, and validate or sign serialized payloads.',
        cheatSheetRefs: ['OWASP Deserialization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_auth_policy.001',
        slug: 'weak-authentication-or-password-policy',
        title: 'Weak authentication or password policy',
        category: 'authentication',
        family: 'family.identity_auth',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-521'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1110'],
            capec: ['CAPEC-49'],
            nist: ['IA-5', 'AC-7'],
        },
        keywords: ['weak password', 'authentication', 'password policy', 'brute force', 'rate limit', 'mfa'],
        negativeKeywords: ['argon2', 'rate limiter', 'mfa enforced', 'identity provider'],
        remediationSummary: 'Enforce strong password rules, add login throttling or MFA where appropriate, and rely on hardened auth providers when possible.',
        cheatSheetRefs: ['OWASP Authentication Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.xss_reflected.001',
        slug: 'reflected-cross-site-scripting',
        title: 'Reflected cross-site scripting',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-79'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-63'],
            nist: ['SI-10', 'SC-34'],
        },
        keywords: ['reflected xss', 'cross site scripting', 'innerhtml', 'document.write', 'unsanitized html'],
        negativeKeywords: ['dompurify', 'escapehtml', 'sanitized', 'textcontent'],
        remediationSummary: 'Encode untrusted output for the target context and sanitize HTML when rich rendering is unavoidable.',
        cheatSheetRefs: ['OWASP Cross Site Scripting Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.xss_stored.001',
        slug: 'stored-cross-site-scripting',
        title: 'Stored cross-site scripting',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-79'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-592'],
            nist: ['SI-10', 'SC-34'],
        },
        keywords: ['stored xss', 'persisted xss', 'saved html', 'render user content'],
        negativeKeywords: ['dompurify', 'escapehtml', 'sanitized', 'textcontent'],
        remediationSummary: 'Sanitize stored content before persistence or render, and apply output encoding at every display boundary.',
        cheatSheetRefs: ['OWASP Cross Site Scripting Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.open_redirect.001',
        slug: 'open-redirect-untrusted-destination',
        title: 'Open redirect through untrusted destination',
        category: 'request-forgery',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-601'],
            owasp: ['A01:2021'],
            apiOwasp: [],
            attack: ['T1185'],
            capec: ['CAPEC-178'],
            nist: ['SI-10'],
        },
        keywords: ['open redirect', 'redirect url', 'returnurl', 'next=', 'untrusted redirect'],
        negativeKeywords: ['allow-list', 'same-origin', 'validated redirect'],
        remediationSummary: 'Restrict redirects to allow-listed destinations or resolve them through server-side route names rather than raw URLs.',
        cheatSheetRefs: ['OWASP Unvalidated Redirects and Forwards Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.csrf_missing_token.001',
        slug: 'missing-csrf-protection-on-state-changing-request',
        title: 'Missing CSRF protection on state-changing request',
        category: 'request-forgery',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Tampering', 'Spoofing'],
        mappings: {
            cwe: ['CWE-352'],
            owasp: ['A01:2021'],
            apiOwasp: [],
            attack: ['T1539'],
            capec: ['CAPEC-62'],
            nist: ['SI-10', 'AC-3'],
        },
        keywords: ['csrf', 'cross site request forgery', 'state changing post', 'missing csrf token'],
        negativeKeywords: ['samesite=strict', 'csrf token', 'double submit cookie'],
        remediationSummary: 'Require anti-CSRF tokens or same-site protections for state-changing browser requests.',
        cheatSheetRefs: ['OWASP Cross-Site Request Forgery Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_cors.001',
        slug: 'overly-permissive-cors-policy',
        title: 'Overly permissive CORS policy',
        category: 'security-misconfiguration',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Information Disclosure', 'Tampering'],
        mappings: {
            cwe: ['CWE-942'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-7'],
        },
        keywords: ['cors', 'access-control-allow-origin', '*', 'allowcredentials', 'permissive origin'],
        negativeKeywords: ['trusted origins', 'specific origin allow-list'],
        remediationSummary: 'Restrict CORS origins, methods, and credential use to explicit trusted callers only.',
        cheatSheetRefs: ['OWASP Cross Origin Resource Sharing Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_jwt_validation.001',
        slug: 'weak-jwt-validation-or-algorithm-trust',
        title: 'Weak JWT validation',
        category: 'authentication',
        family: 'family.identity_auth',
        severity: 'HIGH',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-345'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1606'],
            capec: [],
            nist: ['IA-5', 'AC-3'],
        },
        keywords: ['jwt', 'verify=false', 'alg none', 'missing issuer validation', 'missing audience validation'],
        negativeKeywords: ['issuer check', 'audience check', 'allowed algorithms'],
        remediationSummary: 'Verify signature, issuer, audience, expiry, and accepted algorithms explicitly for every JWT.',
        cheatSheetRefs: ['OWASP JSON Web Token Cheat Sheet for Java'],
    },
    {
        id: 'owlvex.issue.unrestricted_file_upload.001',
        slug: 'unrestricted-file-upload',
        title: 'Unrestricted file upload',
        category: 'upload',
        family: 'family.security_misconfiguration',
        severity: 'HIGH',
        stride: ['Tampering', 'Denial of Service', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-434'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1105'],
            capec: ['CAPEC-650'],
            nist: ['SI-10', 'CM-7'],
        },
        keywords: ['file upload', 'multipart', 'no file type validation', 'arbitrary file'],
        negativeKeywords: ['mime allow-list', 'extension allow-list', 'virus scan'],
        remediationSummary: 'Restrict file types and sizes, store uploads outside executable paths, and scan content before processing.',
        cheatSheetRefs: ['OWASP File Upload Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.mass_assignment.001',
        slug: 'mass-assignment-of-client-supplied-fields',
        title: 'Mass assignment of client-supplied fields',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Tampering', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-915'],
            owasp: ['A01:2021'],
            apiOwasp: ['API6:2023'],
            attack: [],
            capec: [],
            nist: ['AC-6'],
        },
        keywords: ['mass assignment', 'bind request body', 'spread request body', 'assign req.body'],
        negativeKeywords: ['pick(', 'allow-list fields', 'dto validation'],
        remediationSummary: 'Use explicit field allow-lists or DTOs when binding client input into domain models.',
        cheatSheetRefs: ['OWASP Mass Assignment Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.xxe.001',
        slug: 'xml-external-entity-processing',
        title: 'Unsafe XML external entity processing',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-611'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: ['CAPEC-201'],
            nist: ['SI-10'],
        },
        keywords: ['xxe', 'xml external entity', 'doctype', 'xml parser'],
        negativeKeywords: ['disallow-doctype-decl', 'external entities disabled'],
        remediationSummary: 'Disable external entity resolution and DTD processing in XML parsers handling untrusted input.',
        cheatSheetRefs: ['OWASP XML External Entity Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_crypto.001',
        slug: 'weak-or-deprecated-cryptographic-primitive',
        title: 'Weak or deprecated cryptographic primitive',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-327'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-12', 'SC-13'],
        },
        keywords: ['md5', 'sha1', 'des', 'rc4', 'weak crypto', 'deprecated cipher'],
        negativeKeywords: ['argon2', 'aes-256-gcm', 'sha-256', 'bcrypt'],
        remediationSummary: 'Replace deprecated cryptographic algorithms with modern, approved primitives and secure modes.',
        cheatSheetRefs: ['OWASP Cryptographic Storage Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_randomness.001',
        slug: 'insecure-randomness-for-security-sensitive-values',
        title: 'Insecure randomness for security-sensitive values',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-330'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-12'],
        },
        keywords: ['math.random', 'predictable random', 'random token generation'],
        negativeKeywords: ['crypto.randombytes', 'secrets.token', 'secure random'],
        remediationSummary: 'Use a cryptographically secure random source for tokens, keys, and reset links.',
        cheatSheetRefs: ['OWASP Cryptographic Storage Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.verbose_error_disclosure.001',
        slug: 'verbose-error-disclosure-to-clients',
        title: 'Verbose error disclosure to clients',
        category: 'error-handling',
        family: 'family.data_protection_privacy',
        severity: 'MEDIUM',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-209'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1082'],
            capec: [],
            nist: ['SI-11'],
        },
        keywords: ['error.message', 'stack trace', 'internal server error details', 'verbose error'],
        negativeKeywords: ['generic error response', 'safe error message'],
        remediationSummary: 'Return generic client-facing errors and log diagnostic detail only to protected internal telemetry.',
        cheatSheetRefs: ['OWASP Error Handling Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.prototype_pollution.001',
        slug: 'prototype-pollution-through-untrusted-object-merge',
        title: 'Prototype pollution through untrusted object merge',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Elevation of Privilege', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-1321'],
            owasp: ['A08:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SI-10'],
        },
        keywords: ['prototype pollution', '__proto__', 'constructor.prototype', 'merge user object'],
        negativeKeywords: ['hasownproperty', 'safe merge', 'schema validation'],
        remediationSummary: 'Reject dangerous object keys like __proto__ and use safe merge utilities with schema validation.',
        cheatSheetRefs: ['OWASP Prototype Pollution Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.regex_dos.001',
        slug: 'regular-expression-denial-of-service',
        title: 'Regular expression denial of service',
        category: 'availability',
        family: 'family.availability_resilience',
        severity: 'MEDIUM',
        stride: ['Denial of Service'],
        mappings: {
            cwe: ['CWE-1333'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: [],
            capec: ['CAPEC-492'],
            nist: ['SI-10'],
        },
        keywords: ['redos', 'catastrophic backtracking', 'unsafe regex', 'regular expression denial of service'],
        negativeKeywords: ['bounded input', 'safe-regex', 'timeout'],
        remediationSummary: 'Avoid catastrophic regex patterns or enforce bounded input sizes and regex timeouts.',
        cheatSheetRefs: ['OWASP Input Validation Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.template_injection.001',
        slug: 'server-side-template-injection',
        title: 'Server-side template injection',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'CRITICAL',
        stride: ['Tampering', 'Elevation of Privilege', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-94'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-242'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['template injection', 'render template from user input', 'ssti', '{{7*7}}'],
        negativeKeywords: ['trusted template names', 'strict allow-list'],
        remediationSummary: 'Do not evaluate user-controlled template expressions; restrict rendering to trusted templates and escaped data bindings.',
        cheatSheetRefs: ['OWASP Server Side Template Injection Prevention guidance'],
    },
    {
        id: 'owlvex.issue.nosql_injection.001',
        slug: 'nosql-injection-through-untrusted-query-object',
        title: 'NoSQL injection through untrusted query object',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-943'],
            owasp: ['A03:2021'],
            apiOwasp: ['API8:2023'],
            attack: ['T1190'],
            capec: [],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['nosql injection', '$where', '$ne', 'mongo query object', 'untrusted filter'],
        negativeKeywords: ['schema validation', 'allow-list operators'],
        remediationSummary: 'Validate query objects strictly and avoid passing client-controlled operators directly into NoSQL filters.',
        cheatSheetRefs: ['OWASP NoSQL Security Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.ldap_injection.001',
        slug: 'ldap-injection-through-unsanitized-filter',
        title: 'LDAP injection through unsanitized filter',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-90'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: [],
            capec: ['CAPEC-136'],
            nist: ['SI-10'],
        },
        keywords: ['ldap injection', 'ldap filter', '(&(uid=', 'directory search'],
        negativeKeywords: ['ldapescape', 'escaped filter value'],
        remediationSummary: 'Escape LDAP filter input and use safe directory query APIs that separate data from filter syntax.',
        cheatSheetRefs: ['OWASP LDAP Injection Prevention Cheat Sheet'],
    },
];

export function getIssueFamilyDefinition(id: string): IssueFamilyDefinition | undefined {
    return ISSUE_FAMILY_CATALOG.find(item => item.id === id);
}
