export interface CanonicalMappings {
    cwe: string[];
    owasp: string[];
    apiOwasp: string[];
    attack: string[];
    capec: string[];
    nist: string[];
}

export type DetectionLevel = 'direct' | 'flow' | 'inferred' | 'partial';

/**
 * Applicability context for a canonical issue.
 *
 * global      — applies to every codebase unconditionally.
 * conditional — only applies when the required architectural context is detected.
 *               The scanner gates activation on the `requires` signals.
 */
export type IssueApplicability = 'global' | 'conditional';

export interface CanonicalIssue {
    id: string;
    slug: string;
    title: string;
    category: string;
    family: string;
    severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW' | 'INFO';
    stride: string[];
    mappings: CanonicalMappings;
    keywords: string[];
    remediationSummary: string;
    cheatSheetRefs: string[];
    detectionLevel: DetectionLevel;
    requiresTrustTracking: boolean;
    /** Defaults to 'global'. Conditional issues are only surfaced when architectural context is present. */
    applicability: IssueApplicability;
    /** For conditional issues: the architectural context signals required to activate this issue. */
    requires?: string[];
    requiredAnyKeywords?: string[];
    negativeKeywords?: string[];
    minimumScore?: number;
}

type CanonicalIssueDefinition = Omit<CanonicalIssue, 'detectionLevel' | 'requiresTrustTracking' | 'applicability'>
& Partial<Pick<CanonicalIssue, 'detectionLevel' | 'requiresTrustTracking' | 'applicability'>>;

export interface IssueFamilyDefinition {
    id: string;
    label: string;
    description: string;
}

export const ISSUE_FAMILY_CATALOG: IssueFamilyDefinition[] = [
    {
        id: 'family.secrets_exposure',
        label: 'Secrets & Credential Exposure',
        description: 'Hardcoded credentials, token leakage, and other secret-handling weaknesses.',
    },
    {
        id: 'family.injection_execution',
        label: 'Injection & Execution',
        description: 'Injection flaws that let untrusted input alter queries, commands, templates, or interpreters.',
    },
    {
        id: 'family.identity_auth',
        label: 'Identity & Auth Failures',
        description: 'Authentication weaknesses, token validation errors, and account compromise paths.',
    },
    {
        id: 'family.access_control',
        label: 'Access Control & Authorization',
        description: 'Object-level authorization, path access, and unsafe permission boundaries.',
    },
    {
        id: 'family.data_protection_privacy',
        label: 'Data Protection & Privacy',
        description: 'Sensitive logging, disclosure, and unsafe handling of protected data.',
    },
    {
        id: 'family.security_misconfiguration',
        label: 'Security Misconfiguration & Platform Hardening',
        description: 'Unsafe defaults, permissive configuration, and weak runtime hardening.',
    },
    {
        id: 'family.audit_observability',
        label: 'Audit & Observability Gaps',
        description: 'Missing audit trails and weak forensic visibility around sensitive actions.',
    },
    {
        id: 'family.availability_resilience',
        label: 'Availability & Resilience',
        description: 'Patterns that create denial of service or systemic resilience risk.',
    },
    {
        id: 'family.crypto_randomness',
        label: 'Cryptography & Randomness',
        description: 'Weak cryptography, unsafe randomness, and broken security primitives.',
    },
];

function defineIssue(issue: CanonicalIssueDefinition): CanonicalIssue {
    return {
        detectionLevel: 'direct',
        requiresTrustTracking: false,
        applicability: 'global',
        ...issue,
    };
}

const ISSUE_DEFINITIONS: CanonicalIssueDefinition[] = [
    {
        id: 'owlvex.issue.sql_injection.001',
        slug: 'sql-injection-unsanitized-query-construction',
        title: 'SQL Injection',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        detectionLevel: 'flow',
        requiresTrustTracking: true,
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-89'],
            owasp: ['A03:2021'],
            apiOwasp: ['API8:2023'],
            attack: ['T1190'],
            capec: ['CAPEC-66'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['sql injection', 'query', 'parameterized', 'database', 'select * from', 'raw sql', 'preparedstatement', 'cursor.execute', 'f-string sql'],
        negativeKeywords: ['prepared statement', 'parameter array', 'bound parameter', 'setstring(', 'values array'],
        remediationSummary: 'Keep untrusted values out of SQL text by using parameterized queries or prepared statements, and allow-list any dynamic structural tokens such as sort columns or table names.',
        cheatSheetRefs: ['OWASP SQL Injection Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.command_injection.001',
        slug: 'command-injection-unsafe-shell-execution',
        title: 'Command Injection',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'CRITICAL',
        detectionLevel: 'flow',
        requiresTrustTracking: true,
        stride: ['Tampering', 'Elevation of Privilege', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-78'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-88'],
            nist: ['SI-10', 'CM-7'],
        },
        keywords: ['command injection', 'shell', 'exec(', 'exec ', 'spawn', 'child_process', 'arbitrary commands', 'subprocess', 'runtime.exec', 'os.system'],
        negativeKeywords: ['execfile', 'shell: false', 'fixed arguments', 'validated host', 'processbuilder'],
        remediationSummary: 'Remove shell-string execution where possible, call safe library APIs directly, and when process execution is unavoidable pass fixed executables with validated argument lists that keep untrusted data out of command syntax.',
        cheatSheetRefs: ['OWASP OS Command Injection Defense Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_api_key.001',
        slug: 'hardcoded-api-key-in-source',
        title: 'Hardcoded API key in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['api key', 'apikey', 'api_key', 'client secret', 'secret key', 'access key'],
        requiredAnyKeywords: ['api key', 'apikey', 'api_key', 'client secret', 'secret key', 'access key'],
        negativeKeywords: ['username', 'user name', 'admin user'],
        minimumScore: 45,
        remediationSummary: 'Move API keys to a secret manager or environment injection and fail closed if they are missing.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_password.001',
        slug: 'hardcoded-password-in-source',
        title: 'Hardcoded password in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['password', 'dbpassword', 'db password', 'passwd', 'pwd'],
        requiredAnyKeywords: ['password', 'dbpassword', 'db password', 'passwd'],
        negativeKeywords: ['username', 'user name', 'admin user'],
        minimumScore: 45,
        remediationSummary: 'Move passwords to a secret manager or environment injection and fail closed if they are missing.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_token.001',
        slug: 'hardcoded-token-in-source',
        title: 'Hardcoded token in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['token', 'bearer token', 'auth token', 'jwt secret', 'refresh token'],
        requiredAnyKeywords: ['token', 'bearer token', 'auth token', 'jwt secret', 'refresh token'],
        negativeKeywords: ['csrf token generated per request'],
        minimumScore: 45,
        remediationSummary: 'Move static tokens to a secret manager and rotate them out of source control immediately.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.hardcoded_secret.001',
        slug: 'hardcoded-secret-in-source-code',
        title: 'Hardcoded secret in source code',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-798'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1552'],
            capec: ['CAPEC-640'],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['hardcoded secret', 'signing key', 'private key', 'embedded secret', 'credential'],
        requiredAnyKeywords: ['hardcoded secret', 'signing key', 'private key', 'embedded secret', 'secret'],
        negativeKeywords: ['username', 'user name', 'admin user', 'display name', 'ops-admin'],
        minimumScore: 55,
        remediationSummary: 'Move secrets to a secret manager or environment injection and fail closed if they are missing.',
        cheatSheetRefs: ['OWASP Secrets Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.path_traversal.001',
        slug: 'path-traversal-untrusted-filesystem-access',
        title: 'Path Traversal',
        category: 'access-control',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-22'],
            owasp: ['A01:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: ['CAPEC-126'],
            nist: ['AC-6', 'SI-10'],
        },
        keywords: ['path traversal', '../', 'file path', 'path.join', 'filesystem', 'directory boundary', 'paths.get', 'os.path.join'],
        negativeKeywords: ['path.resolve(base', 'startswith(basedir)', 'allow-list', 'fixed identifier map'],
        remediationSummary: 'Bind file access to a fixed base directory or server-side identifier map, normalize before use, and reject any request-derived path that escapes the allowed boundary.',
        cheatSheetRefs: ['OWASP Path Traversal Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.idor.001',
        slug: 'idor-missing-object-level-authorization',
        title: 'Missing object-level authorization',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'HIGH',
        detectionLevel: 'inferred',
        stride: ['Elevation of Privilege', 'Information Disclosure', 'Tampering'],
        mappings: {
            cwe: ['CWE-639'],
            owasp: ['A01:2021'],
            apiOwasp: ['API1:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-233'],
            nist: ['AC-3', 'AC-6'],
        },
        keywords: ['idor', 'object level authorization', 'ownership', 'unauthorized access', 'resource id'],
        negativeKeywords: ['account_id = ?', 'owner_id = ?', 'authorization check', 'policy.enforce'],
        remediationSummary: 'Enforce object-level authorization before read or write operations and scope queries to the authenticated actor.',
        cheatSheetRefs: ['OWASP Authorization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.code_injection.eval.001',
        slug: 'dynamic-code-evaluation-of-untrusted-input',
        title: 'Dynamic code evaluation of untrusted input',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'CRITICAL',
        detectionLevel: 'direct',
        requiresTrustTracking: true,
        stride: ['Tampering', 'Elevation of Privilege', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-95'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-242'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['eval', 'new function', 'dynamic code', 'execute user input', 'code injection'],
        negativeKeywords: ['static expression', 'constant expression', 'trusted expression'],
        minimumScore: 45,
        remediationSummary: 'Do not evaluate user-controlled code; replace dynamic execution with fixed dispatch or validated allow-listed operations.',
        cheatSheetRefs: ['OWASP Injection Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.sensitive_logging.001',
        slug: 'sensitive-data-exposed-in-logs',
        title: 'Sensitive data exposed in logs',
        category: 'logging',
        family: 'family.data_protection_privacy',
        severity: 'MEDIUM',
        // Conditional: only relevant when the source handles identifiable sensitive fields.
        // The scanner gates on presence of known PII/credential field names in the source.
        applicability: 'conditional',
        requires: ['pii_fields_present'],
        stride: ['Information Disclosure', 'Repudiation'],
        mappings: {
            cwe: ['CWE-532'],
            owasp: ['A09:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: [],
            nist: ['AU-9', 'SC-28'],
        },
        keywords: ['log', 'logging', 'sensitive data', 'password in logs', 'token in logs', 'console.log'],
        negativeKeywords: ['redacted', 'masked', '[redacted]'],
        remediationSummary: 'Redact sensitive fields before logging and restrict log content to operationally necessary metadata.',
        cheatSheetRefs: ['OWASP Logging Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.audit_gap.001',
        slug: 'missing-audit-trail-for-privileged-action',
        title: 'Missing audit trail for privileged action',
        category: 'audit',
        family: 'family.audit_observability',
        severity: 'MEDIUM',
        stride: ['Repudiation'],
        mappings: {
            cwe: ['CWE-778'],
            owasp: ['A09:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['AU-2', 'AU-12'],
        },
        keywords: ['audit', 'audit log', 'privileged action', 'traceability', 'no audit', 'missing audit'],
        negativeKeywords: ['audit.log', 'security event', 'immutable audit'],
        remediationSummary: 'Record immutable audit events for privileged actions with actor, action, target, and timestamp metadata.',
        cheatSheetRefs: ['OWASP Logging Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.ssrf.001',
        slug: 'server-side-request-forgery-untrusted-destination',
        title: 'Server-side request forgery (SSRF) through untrusted destination',
        category: 'request-forgery',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Tampering', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-918'],
            owasp: ['A10:2021'],
            apiOwasp: ['API7:2023'],
            attack: ['T1190'],
            capec: ['CAPEC-664'],
            nist: ['SC-7', 'SI-10'],
        },
        keywords: ['ssrf', 'server side request forgery', 'metadata endpoint', 'internal service', 'untrusted url', 'requests.get', 'fetch(', 'openstream'],
        negativeKeywords: ['allowed_hosts', 'allow-list', 'parsed.hostname', 'trusted destination map'],
        remediationSummary: 'Treat request-supplied destinations as control data: route outbound access through an allow-list or named integration, validate protocol and hostname before use, and block internal address ranges and redirects where appropriate.',
        cheatSheetRefs: ['OWASP Server Side Request Forgery Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_deserialization.001',
        slug: 'insecure-deserialization-of-untrusted-data',
        title: 'Insecure Deserialization',
        category: 'deserialization',
        family: 'family.injection_execution',
        severity: 'HIGH',
        detectionLevel: 'direct',
        stride: ['Tampering', 'Elevation of Privilege', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-502'],
            owasp: ['A08:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-586'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['deserialization', 'deserialize', 'pickle', 'untrusted payload', 'binary formatter', 'objectinputstream', 'pickle.loads'],
        negativeKeywords: ['json.parse', 'schema validation', 'signed payload', 'json.loads'],
        remediationSummary: 'Avoid unsafe object deserializers for untrusted input, prefer data-only formats, and validate, sign, or constrain serialized content before any object materialization occurs.',
        cheatSheetRefs: ['OWASP Deserialization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.missing_authentication_check.001',
        slug: 'missing-authentication-check-on-protected-route',
        title: 'Missing authentication check on protected route',
        category: 'authentication',
        family: 'family.identity_auth',
        severity: 'HIGH',
        detectionLevel: 'direct',
        stride: ['Spoofing', 'Elevation of Privilege', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-306'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-115'],
            nist: ['AC-3', 'IA-2'],
        },
        keywords: ['missing authentication', 'protected route', 'admin route', 'unauthenticated access', 'no auth middleware'],
        negativeKeywords: ['requireauth', 'authenticate', 'ensureauthenticated', 'authmiddleware', 'jwt.verify'],
        minimumScore: 45,
        remediationSummary: 'Require authentication middleware or equivalent identity checks before protected handlers execute.',
        cheatSheetRefs: ['OWASP Authentication Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_auth_policy.001',
        slug: 'weak-authentication-or-password-policy',
        title: 'Weak authentication or password policy',
        category: 'authentication',
        family: 'family.identity_auth',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-521'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1110'],
            capec: ['CAPEC-49'],
            nist: ['IA-5', 'AC-7'],
        },
        keywords: ['weak password', 'authentication', 'password policy', 'brute force', 'rate limit', 'mfa'],
        negativeKeywords: ['argon2', 'rate limiter', 'mfa enforced', 'identity provider'],
        remediationSummary: 'Enforce strong password rules, add login throttling or MFA where appropriate, and rely on hardened auth providers when possible.',
        cheatSheetRefs: ['OWASP Authentication Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.xss_reflected.001',
        slug: 'reflected-cross-site-scripting',
        title: 'Reflected cross-site scripting',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-79'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-63'],
            nist: ['SI-10', 'SC-34'],
        },
        keywords: ['reflected xss', 'cross site scripting', 'innerhtml', 'document.write', 'unsanitized html'],
        negativeKeywords: ['dompurify', 'escapehtml', 'sanitized', 'textcontent'],
        remediationSummary: 'Encode untrusted output for the target context and sanitize HTML when rich rendering is unavoidable.',
        cheatSheetRefs: ['OWASP Cross Site Scripting Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.xss_stored.001',
        slug: 'stored-cross-site-scripting',
        title: 'Stored cross-site scripting',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-79'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-592'],
            nist: ['SI-10', 'SC-34'],
        },
        keywords: ['stored xss', 'persisted xss', 'saved html', 'render user content'],
        negativeKeywords: ['dompurify', 'escapehtml', 'sanitized', 'textcontent'],
        remediationSummary: 'Sanitize stored content before persistence or render, and apply output encoding at every display boundary.',
        cheatSheetRefs: ['OWASP Cross Site Scripting Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.open_redirect.001',
        slug: 'open-redirect-untrusted-destination',
        title: 'Open redirect through untrusted destination',
        category: 'request-forgery',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-601'],
            owasp: ['A01:2021'],
            apiOwasp: [],
            attack: ['T1185'],
            capec: ['CAPEC-178'],
            nist: ['SI-10'],
        },
        keywords: ['open redirect', 'redirect url', 'returnurl', 'next=', 'untrusted redirect'],
        negativeKeywords: ['allow-list', 'same-origin', 'validated redirect'],
        remediationSummary: 'Restrict redirects to allow-listed destinations or resolve them through server-side route names rather than raw URLs.',
        cheatSheetRefs: ['OWASP Unvalidated Redirects and Forwards Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.csrf_missing_token.001',
        slug: 'missing-csrf-protection-on-state-changing-request',
        title: 'Missing CSRF protection on state-changing request',
        category: 'request-forgery',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Tampering', 'Spoofing'],
        mappings: {
            cwe: ['CWE-352'],
            owasp: ['A01:2021'],
            apiOwasp: [],
            attack: ['T1539'],
            capec: ['CAPEC-62'],
            nist: ['SI-10', 'AC-3'],
        },
        keywords: ['csrf', 'cross site request forgery', 'state changing post', 'missing csrf token'],
        negativeKeywords: ['samesite=strict', 'csrf token', 'double submit cookie'],
        remediationSummary: 'Require anti-CSRF tokens or same-site protections for state-changing browser requests.',
        cheatSheetRefs: ['OWASP Cross-Site Request Forgery Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_cors.001',
        slug: 'overly-permissive-cors-policy',
        title: 'Overly permissive CORS policy',
        category: 'security-misconfiguration',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Information Disclosure', 'Tampering'],
        mappings: {
            cwe: ['CWE-942'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-7'],
        },
        keywords: ['cors', 'access-control-allow-origin', '*', 'allowcredentials', 'permissive origin'],
        negativeKeywords: ['trusted origins', 'specific origin allow-list'],
        remediationSummary: 'Restrict CORS origins, methods, and credential use to explicit trusted callers only.',
        cheatSheetRefs: ['OWASP Cross Origin Resource Sharing Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_jwt_validation.001',
        slug: 'weak-jwt-validation-or-algorithm-trust',
        title: 'Weak JWT validation',
        category: 'authentication',
        family: 'family.identity_auth',
        severity: 'HIGH',
        detectionLevel: 'direct',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-345'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1606'],
            capec: [],
            nist: ['IA-5', 'AC-3'],
        },
        keywords: ['jwt', 'verify=false', 'alg none', 'missing issuer validation', 'missing audience validation', 'jwt.decode', 'decode without verify', 'verify_signature false'],
        negativeKeywords: ['issuer check', 'audience check', 'allowed algorithms', 'jwt.verify', 'algorithms=['],
        remediationSummary: 'Verify signature, issuer, audience, expiry, and accepted algorithms explicitly for every JWT, and never treat token parsing alone as a trust decision.',
        cheatSheetRefs: ['OWASP JSON Web Token Cheat Sheet for Java'],
    },
    {
        id: 'owlvex.issue.broken_function_level_authorization.001',
        slug: 'broken-function-level-authorization',
        title: 'Broken function-level authorization',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'HIGH',
        detectionLevel: 'direct',
        stride: ['Elevation of Privilege', 'Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-285'],
            owasp: ['A01:2021'],
            apiOwasp: ['API5:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-233'],
            nist: ['AC-3', 'AC-6'],
        },
        keywords: ['function level authorization', 'admin action', 'privileged action', 'role check missing', 'broken function level authorization'],
        negativeKeywords: ['requireadmin', 'requirerole', 'policy.enforce', 'authorizeadmin'],
        minimumScore: 45,
        remediationSummary: 'Protect privileged routes and administrative actions with explicit role or policy checks, not just basic authentication.',
        cheatSheetRefs: ['OWASP Authorization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.unrestricted_file_upload.001',
        slug: 'unrestricted-file-upload',
        title: 'Unrestricted file upload',
        category: 'upload',
        family: 'family.security_misconfiguration',
        severity: 'HIGH',
        stride: ['Tampering', 'Denial of Service', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-434'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1105'],
            capec: ['CAPEC-650'],
            nist: ['SI-10', 'CM-7'],
        },
        keywords: ['file upload', 'multipart', 'no file type validation', 'arbitrary file'],
        negativeKeywords: ['mime allow-list', 'extension allow-list', 'virus scan'],
        remediationSummary: 'Restrict file types and sizes, store uploads outside executable paths, and scan content before processing.',
        cheatSheetRefs: ['OWASP File Upload Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.mass_assignment.001',
        slug: 'mass-assignment-of-client-supplied-fields',
        title: 'Mass assignment of client-supplied fields',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'HIGH',
        stride: ['Tampering', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-915'],
            owasp: ['A01:2021'],
            apiOwasp: ['API6:2023'],
            attack: [],
            capec: [],
            nist: ['AC-6'],
        },
        keywords: ['mass assignment', 'bind request body', 'spread request body', 'assign req.body'],
        negativeKeywords: ['pick(', 'allow-list fields', 'dto validation'],
        remediationSummary: 'Use explicit field allow-lists or DTOs when binding client input into domain models.',
        cheatSheetRefs: ['OWASP Mass Assignment Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.xxe.001',
        slug: 'xml-external-entity-processing',
        title: 'Unsafe XML external entity processing',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-611'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: ['CAPEC-201'],
            nist: ['SI-10'],
        },
        keywords: ['xxe', 'xml external entity', 'doctype', 'xml parser'],
        negativeKeywords: ['disallow-doctype-decl', 'external entities disabled'],
        remediationSummary: 'Disable external entity resolution and DTD processing in XML parsers handling untrusted input.',
        cheatSheetRefs: ['OWASP XML External Entity Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_crypto.001',
        slug: 'weak-or-deprecated-cryptographic-primitive',
        title: 'Weak or deprecated cryptographic primitive',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-327'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-12', 'SC-13'],
        },
        keywords: ['md5', 'sha1', 'des', 'rc4', 'weak crypto', 'deprecated cipher'],
        negativeKeywords: ['argon2', 'aes-256-gcm', 'sha-256', 'bcrypt'],
        remediationSummary: 'Replace deprecated cryptographic algorithms with modern, approved primitives and secure modes.',
        cheatSheetRefs: ['OWASP Cryptographic Storage Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_randomness.001',
        slug: 'insecure-randomness-for-security-sensitive-values',
        title: 'Insecure randomness for security-sensitive values',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-330'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-12'],
        },
        keywords: ['math.random', 'predictable random', 'random token generation'],
        negativeKeywords: ['crypto.randombytes', 'secrets.token', 'secure random'],
        remediationSummary: 'Use a cryptographically secure random source for tokens, keys, and reset links.',
        cheatSheetRefs: ['OWASP Cryptographic Storage Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.verbose_error_disclosure.001',
        slug: 'verbose-error-disclosure-to-clients',
        title: 'Verbose error disclosure to clients',
        category: 'error-handling',
        family: 'family.data_protection_privacy',
        severity: 'MEDIUM',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-209'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1082'],
            capec: [],
            nist: ['SI-11'],
        },
        keywords: ['error.message', 'stack trace', 'internal server error details', 'verbose error'],
        negativeKeywords: ['generic error response', 'safe error message'],
        remediationSummary: 'Return generic client-facing errors and log diagnostic detail only to protected internal telemetry.',
        cheatSheetRefs: ['OWASP Error Handling Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.prototype_pollution.001',
        slug: 'prototype-pollution-through-untrusted-object-merge',
        title: 'Prototype pollution through untrusted object merge',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Elevation of Privilege', 'Denial of Service'],
        mappings: {
            cwe: ['CWE-1321'],
            owasp: ['A08:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SI-10'],
        },
        keywords: ['prototype pollution', '__proto__', 'constructor.prototype', 'merge user object'],
        negativeKeywords: ['hasownproperty', 'safe merge', 'schema validation'],
        remediationSummary: 'Reject dangerous object keys like __proto__ and use safe merge utilities with schema validation.',
        cheatSheetRefs: ['OWASP Prototype Pollution Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.regex_dos.001',
        slug: 'regular-expression-denial-of-service',
        title: 'Regular expression denial of service',
        category: 'availability',
        family: 'family.availability_resilience',
        severity: 'MEDIUM',
        stride: ['Denial of Service'],
        mappings: {
            cwe: ['CWE-1333'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: [],
            capec: ['CAPEC-492'],
            nist: ['SI-10'],
        },
        keywords: ['redos', 'catastrophic backtracking', 'unsafe regex', 'regular expression denial of service'],
        negativeKeywords: ['bounded input', 'safe-regex', 'timeout'],
        remediationSummary: 'Avoid catastrophic regex patterns or enforce bounded input sizes and regex timeouts.',
        cheatSheetRefs: ['OWASP Input Validation Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.template_injection.001',
        slug: 'server-side-template-injection',
        title: 'Server-side template injection',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'CRITICAL',
        stride: ['Tampering', 'Elevation of Privilege', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-94'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: ['T1059'],
            capec: ['CAPEC-242'],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['template injection', 'render template from user input', 'ssti', '{{7*7}}'],
        negativeKeywords: ['trusted template names', 'strict allow-list'],
        remediationSummary: 'Do not evaluate user-controlled template expressions; restrict rendering to trusted templates and escaped data bindings.',
        cheatSheetRefs: ['OWASP Server Side Template Injection Prevention guidance'],
    },
    {
        id: 'owlvex.issue.nosql_injection.001',
        slug: 'nosql-injection-through-untrusted-query-object',
        title: 'NoSQL injection through untrusted query object',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-943'],
            owasp: ['A03:2021'],
            apiOwasp: ['API8:2023'],
            attack: ['T1190'],
            capec: [],
            nist: ['SI-10', 'SA-11'],
        },
        keywords: ['nosql injection', '$where', '$ne', 'mongo query object', 'untrusted filter'],
        negativeKeywords: ['schema validation', 'allow-list operators'],
        remediationSummary: 'Validate query objects strictly and avoid passing client-controlled operators directly into NoSQL filters.',
        cheatSheetRefs: ['OWASP NoSQL Security Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.ldap_injection.001',
        slug: 'ldap-injection-through-unsanitized-filter',
        title: 'LDAP injection through unsanitized filter',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-90'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: [],
            capec: ['CAPEC-136'],
            nist: ['SI-10'],
        },
        keywords: ['ldap injection', 'ldap filter', '(&(uid=', 'directory search'],
        negativeKeywords: ['ldapescape', 'escaped filter value'],
        remediationSummary: 'Escape LDAP filter input and use safe directory query APIs that separate data from filter syntax.',
        cheatSheetRefs: ['OWASP LDAP Injection Prevention Cheat Sheet'],
    },

    // ── Identity & Auth ───────────────────────────────────────────────────────

    {
        id: 'owlvex.issue.session_fixation.001',
        slug: 'session-fixation-pre-authentication-token-reuse',
        title: 'Session fixation — pre-authentication token reused after login',
        category: 'session-management',
        family: 'family.identity_auth',
        severity: 'HIGH',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-384'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1550'],
            capec: ['CAPEC-60'],
            nist: ['IA-8', 'SC-23'],
        },
        keywords: ['session fixation', 'session id', 'pre-login session', 'regenerate session', 'session reuse'],
        negativeKeywords: ['session.regenerate', 'rotatesession', 'newsessionid', 'regenerateid'],
        remediationSummary: 'Regenerate the session identifier immediately after a successful login to invalidate any pre-authentication session.',
        cheatSheetRefs: ['OWASP Session Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.missing_session_expiry.001',
        slug: 'missing-or-excessive-session-token-expiry',
        title: 'Missing or excessive session token expiry',
        category: 'session-management',
        family: 'family.identity_auth',
        severity: 'MEDIUM',
        stride: ['Spoofing', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-613'],
            owasp: ['A07:2021'],
            apiOwasp: ['API2:2023'],
            attack: ['T1550'],
            capec: ['CAPEC-60'],
            nist: ['AC-12', 'SC-23'],
        },
        keywords: ['session expiry', 'session timeout', 'no expiry', 'long-lived token', 'maxage', 'never expires', 'session ttl'],
        negativeKeywords: ['expiresinseconds', 'maxage: 900', 'session timeout configured'],
        remediationSummary: 'Set an absolute session expiry appropriate to the sensitivity of the resource and enforce idle timeout on sensitive flows.',
        cheatSheetRefs: ['OWASP Session Management Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.oauth_state_missing.001',
        slug: 'oauth-csrf-missing-state-parameter',
        title: 'OAuth flow missing state parameter (CSRF in OAuth)',
        category: 'authentication',
        family: 'family.identity_auth',
        severity: 'HIGH',
        stride: ['Spoofing', 'Tampering'],
        mappings: {
            cwe: ['CWE-352'],
            owasp: ['A07:2021'],
            apiOwasp: [],
            attack: ['T1539'],
            capec: ['CAPEC-62'],
            nist: ['IA-8', 'SC-23'],
        },
        keywords: ['oauth state', 'missing state parameter', 'oauth csrf', 'authorization code flow', 'oauth callback'],
        negativeKeywords: ['state parameter verified', 'pkce', 'state validated'],
        remediationSummary: 'Generate an unpredictable state parameter, bind it to the user session, and verify it on the OAuth callback before processing the authorization code.',
        cheatSheetRefs: ['OWASP OAuth Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.insecure_cookie.001',
        slug: 'missing-secure-httponly-samesite-cookie-flags',
        title: 'Missing Secure, HttpOnly, or SameSite flags on session cookie',
        category: 'session-management',
        family: 'family.identity_auth',
        severity: 'MEDIUM',
        // Conditional: only relevant when the source sets HTTP cookies directly.
        // The scanner gates on the presence of cookie-setting calls in the source.
        applicability: 'conditional',
        requires: ['cookie_handling_context'],
        stride: ['Spoofing', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-614'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1539'],
            capec: ['CAPEC-61'],
            nist: ['SC-23', 'AC-17'],
        },
        keywords: ['cookie', 'httponly', 'secure flag', 'samesite', 'session cookie', 'missing cookie flags', 'set-cookie'],
        negativeKeywords: ['httponly: true', 'secure: true', 'samesite: strict', 'samesite: lax'],
        remediationSummary: 'Set Secure, HttpOnly, and SameSite=Strict (or Lax) on all session and authentication cookies.',
        cheatSheetRefs: ['OWASP Session Management Cheat Sheet', 'OWASP Cookie Security Guide'],
    },
    {
        id: 'owlvex.issue.token_exposure_url.001',
        slug: 'sensitive-token-or-credential-in-url-or-query-string',
        title: 'Sensitive token or credential in URL or query string',
        category: 'secrets',
        family: 'family.secrets_exposure',
        severity: 'MEDIUM',
        stride: ['Information Disclosure', 'Spoofing'],
        mappings: {
            cwe: ['CWE-598'],
            owasp: ['A02:2021'],
            apiOwasp: ['API3:2023'],
            attack: ['T1552'],
            capec: [],
            nist: ['SC-28', 'IA-5'],
        },
        keywords: ['token in url', 'api key in query string', 'credential in url', 'access_token=', 'apikey=', 'key= in url', 'secret= in url'],
        negativeKeywords: ['authorization header', 'bearer token in header'],
        remediationSummary: 'Pass authentication credentials and tokens in request headers, not URLs, to prevent leakage through logs, browser history, and referrer headers.',
        cheatSheetRefs: ['OWASP REST Security Cheat Sheet'],
    },

    // ── Data Protection & Privacy ─────────────────────────────────────────────

    {
        id: 'owlvex.issue.pii_overexposure.001',
        slug: 'pii-overexposure-in-api-response',
        title: 'PII or sensitive fields over-exposed in API response',
        category: 'data-protection',
        family: 'family.data_protection_privacy',
        severity: 'HIGH',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-213'],
            owasp: ['A02:2021'],
            apiOwasp: ['API3:2023'],
            attack: ['T1005'],
            capec: [],
            nist: ['SC-28', 'AC-3'],
        },
        keywords: ['pii', 'personal data', 'full user object', 'returning all fields', 'password hash in response', 'ssn', 'date of birth', 'sensitive fields', 'user details'],
        negativeKeywords: ['dto', 'pick(', 'response projection', 'field allow-list'],
        remediationSummary: 'Return only the minimum fields required for the client. Use response DTOs or projection to exclude sensitive internal fields.',
        cheatSheetRefs: ['OWASP REST Security Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.http_over_https.001',
        slug: 'cleartext-transmission-of-sensitive-data',
        title: 'Cleartext transmission of sensitive data over HTTP',
        category: 'transport-security',
        family: 'family.data_protection_privacy',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Tampering'],
        mappings: {
            cwe: ['CWE-319'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1040'],
            capec: ['CAPEC-157'],
            nist: ['SC-8', 'SC-28'],
        },
        keywords: ['http://', 'cleartext', 'no tls', 'unencrypted connection', 'http endpoint'],
        negativeKeywords: ['https://', 'tls', 'ssl', 'hsts'],
        remediationSummary: 'Require HTTPS with HSTS for all sensitive endpoints and redirect HTTP to HTTPS at the infrastructure layer.',
        cheatSheetRefs: ['OWASP Transport Layer Security Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.sensitive_data_cache.001',
        slug: 'sensitive-data-cached-without-expiry-or-protection',
        title: 'Sensitive data cached without expiry or access protection',
        category: 'data-protection',
        family: 'family.data_protection_privacy',
        severity: 'MEDIUM',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-524'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1005'],
            capec: [],
            nist: ['SC-28', 'AU-9'],
        },
        keywords: ['cache sensitive data', 'no cache expiry', 'cache-control: public', 'store credentials in cache', 'redis without ttl', 'session in cache'],
        negativeKeywords: ['cache-control: no-store', 'ttl configured', 'pragma: no-cache'],
        remediationSummary: 'Set appropriate cache TTLs, mark sensitive responses with Cache-Control: no-store, and ensure cached items are scoped to the individual user.',
        cheatSheetRefs: ['OWASP Secure Headers Project'],
    },

    // ── Security Misconfiguration ─────────────────────────────────────────────

    {
        id: 'owlvex.issue.missing_security_headers.001',
        slug: 'missing-http-security-response-headers',
        title: 'Missing HTTP security response headers',
        category: 'security-misconfiguration',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-693'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-8', 'CM-6'],
        },
        keywords: ['missing csp', 'no content security policy', 'no hsts', 'x-frame-options missing', 'security headers absent', 'no x-content-type'],
        negativeKeywords: ['strict-transport-security', 'content-security-policy', 'x-frame-options', 'x-content-type-options'],
        remediationSummary: 'Apply Content-Security-Policy, Strict-Transport-Security, X-Frame-Options, and X-Content-Type-Options as a security header baseline.',
        cheatSheetRefs: ['OWASP Secure Headers Project'],
    },
    {
        id: 'owlvex.issue.debug_mode_production.001',
        slug: 'debug-mode-or-detailed-errors-in-production',
        title: 'Debug mode or framework error detail enabled in production',
        category: 'security-misconfiguration',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-215'],
            owasp: ['A05:2021'],
            apiOwasp: [],
            attack: ['T1082'],
            capec: [],
            nist: ['CM-6', 'SI-11'],
        },
        keywords: ['debug: true', 'debug mode', 'development mode', 'stack trace enabled', 'show errors in production', 'app.debug = true', 'django debug'],
        negativeKeywords: ['debug: false', 'production mode', 'NODE_ENV === production'],
        remediationSummary: 'Disable debug mode in production environments, suppress framework error detail in responses, and log diagnostics only to protected internal sinks.',
        cheatSheetRefs: ['OWASP Error Handling Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.graphql_introspection.001',
        slug: 'graphql-introspection-enabled-in-production',
        title: 'GraphQL introspection enabled in production',
        category: 'security-misconfiguration',
        family: 'family.security_misconfiguration',
        severity: 'MEDIUM',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-200'],
            owasp: ['A05:2021'],
            apiOwasp: ['API9:2023'],
            attack: ['T1083'],
            capec: [],
            nist: ['CM-6', 'SC-7'],
        },
        keywords: ['graphql introspection', 'introspection query', 'schema exposed', '__schema', 'disable introspection'],
        negativeKeywords: ['introspection disabled', 'introspection: false', 'blockfieldsuggestions'],
        remediationSummary: 'Disable GraphQL introspection in production to prevent schema enumeration. Restrict query depth and complexity to limit data extraction.',
        cheatSheetRefs: ['OWASP GraphQL Cheat Sheet'],
    },

    // ── Crypto & Randomness ───────────────────────────────────────────────────

    {
        id: 'owlvex.issue.hardcoded_iv.001',
        slug: 'hardcoded-or-static-initialization-vector',
        title: 'Hardcoded or static IV/nonce in encryption',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'HIGH',
        stride: ['Information Disclosure', 'Tampering'],
        mappings: {
            cwe: ['CWE-330'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-12', 'SC-13'],
        },
        keywords: ['iv = ', 'static iv', 'hardcoded iv', 'static nonce', 'initialization vector', 'fixed nonce'],
        negativeKeywords: ['crypto.randombytes', 'random iv', 'random nonce', 'generateiv'],
        remediationSummary: 'Generate a random IV/nonce using a cryptographically secure source for every encryption operation and store it alongside the ciphertext.',
        cheatSheetRefs: ['OWASP Cryptographic Storage Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.ecb_mode.001',
        slug: 'ecb-cipher-mode-exposes-block-patterns',
        title: 'ECB cipher mode used — blocks identical plaintext identically',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'HIGH',
        stride: ['Information Disclosure'],
        mappings: {
            cwe: ['CWE-327'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['SC-12', 'SC-13'],
        },
        keywords: ['aes/ecb', 'ecb mode', 'ecb padding', 'cipher ecb', 'des/ecb'],
        negativeKeywords: ['aes/gcm', 'aes/cbc', 'aes-256-gcm', 'aes-128-cbc'],
        remediationSummary: 'Replace ECB mode with an authenticated encryption mode such as AES-GCM, which also provides integrity protection.',
        cheatSheetRefs: ['OWASP Cryptographic Storage Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.weak_password_hash.001',
        slug: 'weak-password-hashing-algorithm-or-cost-factor',
        title: 'Weak password hashing algorithm or insufficient cost factor',
        category: 'cryptography',
        family: 'family.crypto_randomness',
        severity: 'HIGH',
        stride: ['Spoofing', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-916'],
            owasp: ['A02:2021'],
            apiOwasp: [],
            attack: ['T1110'],
            capec: [],
            nist: ['IA-5', 'SC-13'],
        },
        keywords: ['md5 password', 'sha1 password', 'unsalted hash', 'weak hash', 'password.hash', 'crypto.createhash for password', 'sha256 password'],
        negativeKeywords: ['bcrypt', 'argon2', 'scrypt', 'pbkdf2 with iterations'],
        remediationSummary: 'Use an adaptive password hashing function (bcrypt, Argon2id, or scrypt) with an appropriate cost factor tuned to your hardware.',
        cheatSheetRefs: ['OWASP Password Storage Cheat Sheet'],
    },

    // ── Injection completeness ────────────────────────────────────────────────

    {
        id: 'owlvex.issue.crlf_injection.001',
        slug: 'crlf-injection-http-response-splitting',
        title: 'CRLF injection / HTTP response splitting',
        category: 'injection',
        family: 'family.injection_execution',
        severity: 'HIGH',
        stride: ['Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-93'],
            owasp: ['A03:2021'],
            apiOwasp: [],
            attack: [],
            capec: ['CAPEC-34'],
            nist: ['SI-10'],
        },
        keywords: ['crlf injection', 'response splitting', 'header injection', '\\r\\n', 'carriage return in header', 'newline in header value'],
        negativeKeywords: ['sanitized header', 'strip crlf', 'encode header value'],
        remediationSummary: 'Strip or reject carriage return and newline characters from any user-controlled value before placing it in an HTTP response header.',
        cheatSheetRefs: ['OWASP HTTP Response Splitting Prevention Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.log_injection.001',
        slug: 'log-injection-through-user-controlled-input',
        title: 'Log injection through user-controlled input',
        category: 'logging',
        family: 'family.audit_observability',
        severity: 'MEDIUM',
        stride: ['Repudiation', 'Tampering'],
        mappings: {
            cwe: ['CWE-117'],
            owasp: ['A09:2021'],
            apiOwasp: [],
            attack: [],
            capec: [],
            nist: ['AU-9', 'SI-10'],
        },
        keywords: ['log injection', 'user input in log', 'unescaped log entry', 'newline in log', 'forge log entry', 'log unsanitized request'],
        negativeKeywords: ['sanitized log', 'escaped log value', 'structured logging'],
        remediationSummary: 'Sanitize user-controlled values before logging by stripping control characters, or use structured logging that separates data from log format.',
        cheatSheetRefs: ['OWASP Logging Cheat Sheet'],
    },

    // ── Availability & Resilience ─────────────────────────────────────────────

    {
        id: 'owlvex.issue.rate_limit_missing.001',
        slug: 'missing-rate-limiting-on-sensitive-endpoint',
        title: 'Missing rate limiting on authentication or sensitive endpoint',
        category: 'availability',
        family: 'family.availability_resilience',
        severity: 'MEDIUM',
        stride: ['Denial of Service', 'Spoofing'],
        mappings: {
            cwe: ['CWE-307'],
            owasp: ['A07:2021'],
            apiOwasp: ['API4:2023'],
            attack: ['T1110'],
            capec: ['CAPEC-49'],
            nist: ['SC-5', 'AC-7'],
        },
        keywords: ['no rate limit', 'missing rate limit', 'brute force', 'login endpoint', 'unlimited retries', 'no throttling'],
        negativeKeywords: ['rate limiter', 'throttle', 'ratelimit', 'expressratelimit', 'account lockout'],
        remediationSummary: 'Apply rate limiting and account lockout on authentication and other sensitive endpoints; return 429 and use exponential backoff.',
        cheatSheetRefs: ['OWASP Authentication Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.missing_timeout.001',
        slug: 'missing-timeout-on-external-call',
        title: 'Missing timeout on external HTTP, database, or queue call',
        category: 'availability',
        family: 'family.availability_resilience',
        severity: 'MEDIUM',
        stride: ['Denial of Service'],
        mappings: {
            cwe: ['CWE-400'],
            owasp: ['A05:2021'],
            apiOwasp: ['API4:2023'],
            attack: [],
            capec: ['CAPEC-469'],
            nist: ['SC-5', 'SI-17'],
        },
        keywords: ['no timeout', 'missing timeout', 'indefinite wait', 'axios without timeout', 'fetch without abort', 'db query no timeout', 'queue consumer no timeout'],
        negativeKeywords: ['timeout: ', 'abortsignal', 'connection timeout', 'request timeout'],
        remediationSummary: 'Set an explicit timeout on all outbound HTTP, database, and queue calls, and handle the resulting error with an appropriate fallback.',
        cheatSheetRefs: ['OWASP REST Security Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.unbounded_query.001',
        slug: 'unbounded-database-query-without-pagination',
        title: 'Unbounded database query without pagination or result limit',
        category: 'availability',
        family: 'family.availability_resilience',
        severity: 'MEDIUM',
        stride: ['Denial of Service', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-400'],
            owasp: ['A05:2021'],
            apiOwasp: ['API4:2023'],
            attack: [],
            capec: [],
            nist: ['SC-5'],
        },
        keywords: ['no limit', 'no pagination', 'select * without limit', 'fetch all records', 'missing limit clause', 'unbounded result set'],
        negativeKeywords: ['limit ?', 'take(', 'paginate(', 'offset/limit', 'page size'],
        remediationSummary: 'Enforce a maximum page size on list queries, require callers to supply pagination parameters, and reject or cap unbounded requests.',
        cheatSheetRefs: ['OWASP REST Security Cheat Sheet'],
    },

    // ── Access Control depth ──────────────────────────────────────────────────

    {
        id: 'owlvex.issue.unprotected_admin_route.001',
        slug: 'administrative-route-without-access-controls',
        title: 'Administrative or internal route without access controls',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'CRITICAL',
        stride: ['Elevation of Privilege', 'Tampering', 'Information Disclosure'],
        mappings: {
            cwe: ['CWE-285'],
            owasp: ['A01:2021'],
            apiOwasp: ['API5:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-115'],
            nist: ['AC-3', 'AC-6'],
        },
        keywords: ['admin route', 'admin endpoint', 'management api', 'internal route', 'no auth on admin', 'debug endpoint exposed', 'admin panel unprotected'],
        negativeKeywords: ['requireadmin', 'isadmin', 'admin middleware', 'admin role check'],
        minimumScore: 45,
        remediationSummary: 'Protect all administrative and internal management routes with explicit role checks and never expose debug or admin endpoints to unauthenticated callers.',
        cheatSheetRefs: ['OWASP Authorization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.privilege_escalation.001',
        slug: 'privilege-escalation-via-unvalidated-role-assignment',
        title: 'Privilege escalation via unvalidated role or permission assignment',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'HIGH',
        detectionLevel: 'inferred',
        stride: ['Elevation of Privilege', 'Tampering'],
        mappings: {
            cwe: ['CWE-269'],
            owasp: ['A01:2021'],
            apiOwasp: ['API5:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-122'],
            nist: ['AC-6', 'AC-3'],
        },
        keywords: ['role assignment', 'assign role', 'grant permission', 'update role', 'privilege escalation', 'elevate role', 'change user role'],
        negativeKeywords: ['requires admin to assign', 'only admin can assign', 'role change audited'],
        minimumScore: 45,
        remediationSummary: 'Require explicit authorization before assigning roles or permissions, audit every privilege change, and prevent users from self-elevating via API.',
        cheatSheetRefs: ['OWASP Authorization Cheat Sheet'],
    },
    {
        id: 'owlvex.issue.tenant_isolation_missing.001',
        slug: 'multi-tenant-data-isolation-failure',
        title: 'Multi-tenant data isolation failure — cross-tenant data access',
        category: 'authorization',
        family: 'family.access_control',
        severity: 'CRITICAL',
        detectionLevel: 'inferred',
        // Conditional: only relevant when the codebase operates a multi-tenant model.
        // The scanner gates activation on the presence of tenant context signals
        // (tenantId, organizationId, workspaceId, accountId) in the source.
        applicability: 'conditional',
        requires: ['multi_tenant_context'],
        stride: ['Information Disclosure', 'Tampering', 'Elevation of Privilege'],
        mappings: {
            cwe: ['CWE-284'],
            owasp: ['A01:2021'],
            apiOwasp: ['API1:2023'],
            attack: ['T1078'],
            capec: ['CAPEC-122'],
            nist: ['AC-3', 'AC-4', 'SC-2'],
        },
        keywords: ['tenant isolation', 'cross tenant', 'organisation id', 'tenant id missing', 'multi-tenant', 'missing tenant filter', 'data leakage between tenants', 'tenant context'],
        negativeKeywords: ['tenantId in query', 'tenant_id = ?', 'tenant filter applied', 'row level security'],
        minimumScore: 45,
        remediationSummary: 'Scope every data operation to the authenticated tenant context. Enforce tenant_id in all queries and use row-level security or tenant-scoped repositories at the persistence layer.',
        cheatSheetRefs: ['OWASP Authorization Cheat Sheet'],
    },
];

export const ISSUE_CATALOG: CanonicalIssue[] = ISSUE_DEFINITIONS.map(defineIssue);

export function getIssueFamilyDefinition(id: string): IssueFamilyDefinition | undefined {
    return ISSUE_FAMILY_CATALOG.find(item => item.id === id);
}
